### ISSUE TITLE
The picture in Rstudio is displayed in Chinese

### ISSUE THREAD

**Issue by JTCDCTWB** [davidgohel/flextable#579]
As a user of Officeverse，I am really grateful for your contributions!

Meanwhile, a BUG was found during application, that is after loading any package of "flextable", "officer" and "officedown", the images with Chinese characters could not be plotted into Chinese in Rstudio. If the images with Chinese characters was plotted first, then   loading the above three packages, everything is OK.

R：4.3.1；
Rstudio：2023.09.0 Build 463；
Operating System：Win11(22H2) or Win10(LTSC 2019 21H2)

Looking forward to your reply at your earliest convenience.
![1](https://github.com/davidgohel/flextable/assets/64447691/2dd9b2c3-0fbb-445a-957d-30c6d0a14dc4)

**Restart Rstudio**

![2](https://github.com/davidgohel/flextable/assets/64447691/85a28a90-e5a7-40c0-904f-64e7936bcdfa)

**Comment by davidgohel** [comment]
hello,

What happen if you use ragg in RStudio default plot settings? Does it solve the issue?

<img width="620" alt="Capture d’écran 2023-10-13 à 07 37 38" src="https://github.com/davidgohel/flextable/assets/4331618/5c5926c2-7368-4e5b-9ad3-35269fe7eadc">


KR

**Comment by JTCDCTWB** [comment]
Thank you very much for your warm reply!
 According to your suggestion the  problem was solved! 
















At 2023-10-13 13:38:23, "David Gohel" ***@***.***> wrote:

hello,

What happen if you use ragg in RStudio default plot settings? Does it solve the issue?

KR

**Comment by JTCDCTWB** [comment]
*Thank you so much for your work!




Draw pictures in "officedown" with word exported in Chinese, sometimes the picture is not displayed, sometimes the Chinese is not displayed. The code is as follows:




output: 

  officedown::rdocx_document:

---

```{r echo=FALSE}

library(ggplot2)

df <- data.frame(性别 = c("男","女"),

                 人数 = c(48,45))

ggplot(df,aes(x = 性别,y = 人数,fill = 性别)) +

  geom_bar(stat = "identity")

```




![1](https://github.com/davidgohel/officedown/assets/64447691/5c9f9412-1bad-496f-81c3-aeaf66ccc370)

![2](https://github.com/davidgohel/officedown/assets/64447691/7972fb9d-1faf-40b3-a3e9-0aa809f4e176)




Operating environment:

Windows 11 22H2

R version 4.3.1

Rstudio version 2023.09.0 Build 463

officedown version 0.3.1



The above problems have been reported to officedown
















At 2023-10-13 13:38:23, "David Gohel" ***@***.***> wrote:

hello,

What happen if you use ragg in RStudio default plot settings? Does it solve the issue?

KR

**Comment by davidgohel** [comment]
What happen if you use ragg in knitr settings? Does it solve the issue?

```
knitr::opts_chunk$set(dev="ragg_png")
```

**Comment by JTCDCTWB** [comment]
Thank you！Problem solved.

**Comment by davidgohel** [comment]
The issue (not solved or not documented yet) will need some work. Package 'ragg' is used by flextable, but I don't understand why it conflicts with your environment. This has already been reported. I will close the issue when it will be solved. Thank you for opening the issue!

**Comment by davidgohel** [comment]
Closing this one, as it is most likely no longer relevant. 

I could not identify a mechanism in flextable/officer/gdtools that would explain the behavior. The natural suspect was the old Fontconfig setup of 'gdtools' (which could have explained why loading order mattered), but it turned out that 'gdtools' stopped using Fontconfig back in 2019, and at the time of this report the related functions were already inert. Today's 'gdtools' (>= 0.5) has no load-time font side effect at all, and flextable generates its own images with 'ragg'.

My remaining hypothesis is an interaction outside of these packages: loading the 'gdtools' DLL (which bundles cairo/freetype on Windows) in the same process as the RStudio plots rendering engine altered how fonts were resolved for CJK text. This is consistent with the fact that switching the RStudio graphics backend to 'ragg' (which resolves fonts through 'systemfonts') fixed it immediately.

The environment of this report (R 4.3.1, RStudio 2023.09, gdtools 0.3.x) is long gone, and 'ragg' / `dev = "ragg_png"` has since become the standard recommendation. For CJK or other non-Latin scripts, this remains the robust configuration:

- RStudio: *Options > General > Graphics > Backend: AGG*
- knitr / R Markdown / Quarto: `knitr::opts_chunk$set(dev = "ragg_png")`

If anyone can still reproduce this with a current stack (R >= 4.4, recent RStudio, gdtools >= 0.5), please open a new issue. Thanks again for the detailed report
